[lb]
nginx ansible_host=192.168.0.205

[app]
app-1 ansible_host=192.168.0.201
app-2 ansible_host=192.168.0.202

[db]
postgres ansible_host=192.168.0.203

[cache]
redis ansible_host=192.168.0.204

[all:vars]
ansible_user=estrela
ansible_python_interpreter=/usr/bin/python3
